### PR TITLE
NUI-1695 replace mock-require with proxyquire

### PR DESCRIPTION
**Pull request by jdelbick**
## Description

These failing tests were blocking my progress on using the newer version of node-httptransfer in this repo: https://jira.corp.adobe.com/browse/NUI-1644, so I fixed them

Fixes #  https://jira.corp.adobe.com/browse/NUI-1695

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by pheenomenon — APPROVED** [review]

**Comment by pheenomenon** [comment]
Node 10.19 is failing.

**Comment by jdelbick** [comment]
@pheenomenon  I know. I am very confused why this would only start failing now. even weirder, it only fails when I run `npm test` and not when I run the test individually via the vscode test runner

I can reproduce it on master:
1. `git checkout master`
2. `nvm use 10`
3. `npm test`
```

  16) type.js
       file tool fallback
         "after each" hook for "provides a fallback if the file command fails":
     TypeError: stack[position].getFileName is not a function
      at getCallerFile (node_modules/get-caller-file/index.js:22:44)
      at Function.stopMocking [as stop] (node_modules/mock-require/index.js:44:22)
      at Context.<anonymous> (test/utils/type.test.js:72:25)
```

**Comment by jdelbick** [comment]
Unfortunately looks like the "quick fix" attemped here doesn't work for nodejs10.

**Review by pheenomenon — APPROVED** [review]
LGTM, thanks!
Was trying to reason the choice of `require('proxyquire').noCallThru()` vs `require('proxyquire')` in few of the tests. 
`require('proxyquire')`  may work, unless there is a specific reason to use noCallThru.

**Comment by jdelbick** [comment]
@pheenomenon you are correct, in our cases now it may not be needed, I can remove it. 
I figured it was safer to use so things are not mocked that we don't mock explicitely

**Pull request merged**
